### ISSUE TITLE
r.recognize is deprecated?

### ISSUE THREAD

**Issue by Kaixhin** [aigamedev/pmgai-hal9000#1]
I'm not sure which version you're working with, but with [SpeechRecognition 3.1.3](https://pypi.python.org/pypi/SpeechRecognition/3.1.3), `r.recognize` fails. It seems that the backend needs to be provided, so I'm using `r.recognize_google` instead. I assume the same problem exists [here](https://github.com/aigamedev/resistance/blob/master/mods/speech.py).

**Comment by Kaixhin** [comment]
The errors it throws are different as well - it's now `sr.UnknownValueError` and `sr.RequestError`. I've got a working implementation [here](https://github.com/Kaixhin/pmgai-hal9000/blob/master/main.py).

**Comment by alexjc** [comment]
Ah, I had an older version of SpeechRecognition. Thanks for pointing this out!
